apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-python-03231454-gh-gitops
  description: This is GitOps manifest for demo-python-03231454-gh   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=demo-python-03231454-gh
    backstage.io/kubernetes-id: demo-python-03231454-gh 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: roming22-org/demo-python-03231454-gh-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:demo-python-03231454-gh
